// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbeJTFB4Dky6XaGzm1GacnElKID1ekKvE',
    appId: '1:844208962173:web:d8883dd8b373ab46e5cf14',
    messagingSenderId: '844208962173',
    projectId: 'form-management-ibm',
    authDomain: 'form-management-ibm.firebaseapp.com',
    storageBucket: 'form-management-ibm.firebasestorage.app',
    measurementId: 'G-PV3C9PMTGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbf5oOwx5xLYSqY2INggnZkC3UrwDJ5Vs',
    appId: '1:844208962173:android:76a6a4cc1264c02de5cf14',
    messagingSenderId: '844208962173',
    projectId: 'form-management-ibm',
    storageBucket: 'form-management-ibm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQLqPaxP9IX85oa1hMT2ZzuRF2XVgyvhE',
    appId: '1:844208962173:ios:1c85902ddf135aa8e5cf14',
    messagingSenderId: '844208962173',
    projectId: 'form-management-ibm',
    storageBucket: 'form-management-ibm.firebasestorage.app',
    iosBundleId: 'com.example.formManager',
  );
}
